CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "levels_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(30) NOT NULL,
  "title" varchar(30) NOT NULL,
  "level_course_id" int NOT NULL,
  "teacher" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "student_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users_courses" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_course_id") REFERENCES "levels_courses" ("id");


/* ===== CATEGORIES ===== */
INSERT INTO categories (name) VALUES ('frontend');

INSERT INTO categories (name) VALUES ('backend');


/* ===== LEVEL COURSES ===== */
INSERT INTO levels_courses (title) VALUES ('beginner');

INSERT INTO levels_courses (title) VALUES ('advanced');

INSERT INTO levels_courses (title) VALUES ('intermediate');

/* ===== ROLES ===== */
INSERT INTO roles (name) VALUES ('student'); 

INSERT INTO roles (name) VALUES   ('teacher');

INSERT INTO roles (name) VALUES ('admin');

/* ===== USERS ===== */

INSERT INTO users (name, email, password, age, rol_id) VALUES ('veronica', 'veronica.perez@ukuepa.com', 1234, 30, 1);

INSERT INTO users (name, email, password, age, rol_id) VALUES ('Alejandra', 'alejandra@academlo.com', 1234, 30, 2);

INSERT INTO users (name, email, password, age, rol_id) VALUES ('Benjamin', 'Benjamin@academlo.com', 1234, 34, 2);

INSERT INTO users (name, email, password, age, rol_id) VALUES ('Ian', 'ian@academlo.com', 1234, 40, 2);


/* ===== COURSES ===== */
INSERT INTO courses (description, title, level_course_id, teacher, category_id) VALUES ('fundamentos', 'JavaScript', 1, 2, 1);

INSERT INTO courses (description, title, level_course_id, teacher, category_id) VALUES ('estados', 'React', 2, 3, 1);

INSERT INTO courses (description, title, level_course_id, teacher, category_id) VALUES ('sequelize', 'NodeJs', 3, 4, 2);


/* ===== COURSE_VIDEO ===== */
INSERT INTO course_videos (title, url, course_id) VALUES ('introduccion JS', 'acedemlo.com/video1', 1);

INSERT INTO course_videos (title, url, course_id) VALUES ('useState', 'acedemlo.com/react/video1', 2);

INSERT INTO course_videos (title, url, course_id) VALUES ('NodeJS', 'acedemlo.com/NodeJs/video1', 3);


/* ===== USERS_COURSES ===== */

INSERT INTO users_courses (student_id, course_id) VALUES (1, 1);

INSERT INTO users_courses (student_id, course_id) VALUES (1, 2);

INSERT INTO users_courses (student_id, course_id) VALUES (1, 3);

